
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RiskAssessment
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_ActionPlan_FoodNutrient
{

    public int ID { get; set; }

    public string FoodName { get; set; }

    public int NutrientID { get; set; }

    public string NutrientName { get; set; }

    public double Value { get; set; }

    public string Unit { get; set; }

    public int Rank { get; set; }



    public virtual tbl_ActionPlan_Nutrient tbl_ActionPlan_Nutrient { get; set; }

}

}
