
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RiskAssessment
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_ActionPlan_Nutrient
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_ActionPlan_Nutrient()
    {

        this.tbl_ActionPlan_FoodNutrient = new HashSet<tbl_ActionPlan_FoodNutrient>();

        this.tbl_ActionPlan_Nutrition = new HashSet<tbl_ActionPlan_Nutrition>();

    }


    public int ID { get; set; }

    public string Nutrient_RawName { get; set; }

    public string NutrientName { get; set; }

    public string Unit { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbl_ActionPlan_FoodNutrient> tbl_ActionPlan_FoodNutrient { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbl_ActionPlan_Nutrition> tbl_ActionPlan_Nutrition { get; set; }

}

}
